import type {
  PatternPreset,
  PatternStrategy,
  GeometricPreset,
  StripePreset,
  DotPreset,
  CheckerPreset,
  WavePreset,
  CrosshatchGeoPreset,
  HerringbonePreset,
  TilePreset,
  TrianglePreset,
  DiamondPreset,
  HexagonPreset,
  StarPreset,
  CirclePreset,
  JapanesePreset,
  LatticePreset,
  PlaidPreset,
  CubePreset,
  LeafPreset,
  FloralPreset,
  MemphisPreset,
  EyePreset,
  SpiralPreset,
  TerrazzoPreset,
  SquarePreset,
  OctagonPreset,
  ScalePreset,
  ChainlinkPreset,
  EthnicPreset,
} from "./types.js";

/**
 * Built-in pattern presets for common illustration techniques.
 * Agents can use preset names as shorthand for strategy + render configuration.
 */
export const PATTERN_PRESETS: Record<string, PatternPreset> = {
  "hatch-light": {
    strategy: { type: "hatch", angle: 45, spacing: 12 },
    lineWidth: 2,
  },
  "hatch-medium": {
    strategy: { type: "hatch", angle: 45, spacing: 8 },
    lineWidth: 3,
  },
  "hatch-dense": {
    strategy: { type: "hatch", angle: 45, spacing: 4 },
    lineWidth: 2,
  },
  "crosshatch-light": {
    strategy: { type: "crosshatch", angles: [45, 135], spacing: 12, passDecay: 0.7 },
    lineWidth: 2,
  },
  "crosshatch-dense": {
    strategy: { type: "crosshatch", angles: [45, 135], spacing: 5, passDecay: 0.8 },
    lineWidth: 2,
  },
  "stipple-light": {
    strategy: { type: "stipple", density: 15, distribution: "poisson" },
    lineWidth: 2,
  },
  "stipple-dense": {
    strategy: { type: "stipple", density: 60, distribution: "poisson" },
    lineWidth: 2,
  },
  scumble: {
    strategy: { type: "scumble", density: 12, strokeLength: 25, curvature: 0.5 },
    lineWidth: 3,
  },
  contour: {
    strategy: { type: "contour", spacing: 6, smoothing: 0.3 },
    lineWidth: 2,
  },
  "stipple-gradient": {
    strategy: { type: "stipple", density: 40, distribution: "jittered-grid" },
    lineWidth: 3,
  },
  "crosshatch-triple": {
    strategy: { type: "crosshatch", angles: [30, 90, 150], spacing: 8, passDecay: 0.65 },
    lineWidth: 2,
  },
};

// ---------------------------------------------------------------------------
// Geometric pattern presets (stripe, dot, checker, wave)
// ---------------------------------------------------------------------------

export const GEOMETRIC_PRESETS: Record<string, GeometricPreset> = {
  // Stripe presets (6)
  pinstripe: {
    layerType: "patterns:stripe",
    angle: 90,
    spacing: 12,
    lineWidth: 1,
    colors: ["#1a1a2e", "#f0f0f0"],
  },
  ticking: {
    layerType: "patterns:stripe",
    angle: 90,
    spacing: 20,
    lineWidth: 3,
    colors: ["#2c3e50", "#ecf0f1"],
  },
  awning: {
    layerType: "patterns:stripe",
    angle: 90,
    spacing: 30,
    lineWidth: 30,
    colors: ["#c0392b", "#ffffff"],
  },
  nautical: {
    layerType: "patterns:stripe",
    angle: 0,
    spacing: 16,
    lineWidth: 8,
    colors: ["#2c3e50", "#ffffff"],
  },
  candy: {
    layerType: "patterns:stripe",
    angle: 45,
    spacing: 14,
    lineWidth: 14,
    colors: ["#e74c3c", "#ffffff", "#e74c3c", "#ffffff"],
  },
  "barber-pole": {
    layerType: "patterns:stripe",
    angle: 30,
    spacing: 12,
    lineWidth: 12,
    colors: ["#e74c3c", "#ffffff", "#2980b9", "#ffffff"],
  },

  // Dot presets (6)
  "polka-small": {
    layerType: "patterns:dot",
    spacing: 20,
    radius: 4,
    offset: false,
    color: "#2c3e50",
    backgroundColor: "#ffffff",
  },
  "polka-large": {
    layerType: "patterns:dot",
    spacing: 40,
    radius: 12,
    offset: false,
    color: "#e74c3c",
    backgroundColor: "#ffffff",
  },
  halftone: {
    layerType: "patterns:dot",
    spacing: 8,
    radius: 3,
    offset: true,
    color: "#000000",
    backgroundColor: "#ffffff",
  },
  "hex-dot": {
    layerType: "patterns:dot",
    spacing: 24,
    radius: 6,
    offset: true,
    color: "#8e44ad",
    backgroundColor: "#f8f8f8",
  },
  confetti: {
    layerType: "patterns:dot",
    spacing: 16,
    radius: 3,
    offset: true,
    color: "#e67e22",
    backgroundColor: "#fdf2e9",
  },
  sprinkle: {
    layerType: "patterns:dot",
    spacing: 12,
    radius: 2,
    offset: false,
    color: "#27ae60",
    backgroundColor: "#eafaf1",
  },

  // Checker presets (5)
  "checker-small": {
    layerType: "patterns:checker",
    cellSize: 16,
    colors: ["#000000", "#ffffff"],
    angle: 0,
  },
  "checker-large": {
    layerType: "patterns:checker",
    cellSize: 48,
    colors: ["#000000", "#ffffff"],
    angle: 0,
  },
  gingham: {
    layerType: "patterns:checker",
    cellSize: 20,
    colors: ["#3498db", "#d6eaf8"],
    angle: 0,
  },
  "buffalo-check": {
    layerType: "patterns:checker",
    cellSize: 36,
    colors: ["#c0392b", "#1a1a1a"],
    angle: 0,
  },
  houndstooth: {
    layerType: "patterns:checker",
    cellSize: 12,
    colors: ["#2c3e50", "#ecf0f1"],
    angle: 45,
  },

  // Wave presets (5)
  "gentle-wave": {
    layerType: "patterns:wave",
    amplitude: 12,
    frequency: 2,
    phase: 0,
    lineWidth: 2,
    waveform: "sine",
    color: "#2980b9",
    spacing: 30,
  },
  choppy: {
    layerType: "patterns:wave",
    amplitude: 8,
    frequency: 8,
    phase: 0,
    lineWidth: 1.5,
    waveform: "sine",
    color: "#2c3e50",
    spacing: 20,
  },
  zigzag: {
    layerType: "patterns:wave",
    amplitude: 10,
    frequency: 6,
    phase: 0,
    lineWidth: 2,
    waveform: "triangle",
    color: "#e74c3c",
    spacing: 25,
  },
  scallop: {
    layerType: "patterns:wave",
    amplitude: 15,
    frequency: 4,
    phase: 0,
    lineWidth: 2,
    waveform: "sine",
    color: "#16a085",
    spacing: 32,
  },
  ogee: {
    layerType: "patterns:wave",
    amplitude: 20,
    frequency: 2,
    phase: 0,
    lineWidth: 3,
    waveform: "sine",
    color: "#8e44ad",
    spacing: 45,
  },

  // Crosshatch-geo presets (4)
  "fine-crosshatch": {
    layerType: "patterns:crosshatch-geo",
    angle1: 45,
    angle2: 135,
    spacing: 6,
    lineWidth: 0.5,
    color: "#1a1a1a",
    backgroundColor: "#ffffff",
  },
  "bold-crosshatch": {
    layerType: "patterns:crosshatch-geo",
    angle1: 45,
    angle2: 135,
    spacing: 12,
    lineWidth: 2,
    color: "#2c3e50",
    backgroundColor: "#f8f8f8",
  },
  "diamond-mesh": {
    layerType: "patterns:crosshatch-geo",
    angle1: 60,
    angle2: 120,
    spacing: 10,
    lineWidth: 1,
    color: "#34495e",
    backgroundColor: "#ecf0f1",
  },
  screen: {
    layerType: "patterns:crosshatch-geo",
    angle1: 0,
    angle2: 90,
    spacing: 8,
    lineWidth: 0.5,
    color: "#000000",
    backgroundColor: "#ffffff",
  },

  // Herringbone presets (4)
  "classic-herringbone": {
    layerType: "patterns:herringbone",
    blockWidth: 30,
    blockHeight: 10,
    angle: 45,
    color1: "#8b7355",
    color2: "#d4c5a9",
    gap: 1,
  },
  chevron: {
    layerType: "patterns:herringbone",
    blockWidth: 24,
    blockHeight: 8,
    angle: 45,
    color1: "#2c3e50",
    color2: "#ecf0f1",
    gap: 2,
  },
  twill: {
    layerType: "patterns:herringbone",
    blockWidth: 16,
    blockHeight: 8,
    angle: 45,
    color1: "#34495e",
    color2: "#bdc3c7",
    gap: 1,
  },
  parquet: {
    layerType: "patterns:herringbone",
    blockWidth: 40,
    blockHeight: 12,
    angle: 45,
    color1: "#a0522d",
    color2: "#deb887",
    gap: 1,
  },

  // Tile presets (5)
  brick: {
    layerType: "patterns:tile",
    tileShape: "brick",
    size: 30,
    color1: "#c0392b",
    color2: "#95a5a6",
    gap: 2,
  },
  basketweave: {
    layerType: "patterns:tile",
    tileShape: "basketweave",
    size: 20,
    color1: "#8b7355",
    color2: "#d4c5a9",
    gap: 1,
  },
  hexagonal: {
    layerType: "patterns:tile",
    tileShape: "hex",
    size: 24,
    color1: "#2980b9",
    color2: "#d6eaf8",
    gap: 2,
  },
  "fish-scale": {
    layerType: "patterns:tile",
    tileShape: "scale",
    size: 20,
    color1: "#16a085",
    color2: "#d5f5e3",
    gap: 1,
  },
  moroccan: {
    layerType: "patterns:tile",
    tileShape: "moroccan",
    size: 24,
    color1: "#8e44ad",
    color2: "#f5eef8",
    gap: 2,
  },

  // Triangle presets (6)
  "equilateral-grid": {
    layerType: "patterns:triangle",
    style: "equilateral",
    size: 30,
    color1: "#2c3e50",
    color2: "#ecf0f1",
    gap: 1,
  },
  pinwheel: {
    layerType: "patterns:triangle",
    style: "pinwheel",
    size: 36,
    color1: "#e74c3c",
    color2: "#f5b7b1",
    gap: 1,
  },
  "arrow-tessellation": {
    layerType: "patterns:triangle",
    style: "arrow",
    size: 28,
    color1: "#1a5276",
    color2: "#d4e6f1",
    gap: 1,
  },
  kaleidoscope: {
    layerType: "patterns:triangle",
    style: "kaleidoscope",
    size: 40,
    color1: "#8e44ad",
    color2: "#d7bde2",
    gap: 1,
  },
  "inverted-triangles": {
    layerType: "patterns:triangle",
    style: "inverted",
    size: 24,
    color1: "#16a085",
    color2: "#d5f5e3",
    gap: 2,
  },
  "triangle-strip": {
    layerType: "patterns:triangle",
    style: "strip",
    size: 20,
    color1: "#d35400",
    color2: "#fdebd0",
    gap: 1,
  },

  // Diamond presets (5)
  "simple-diamond": {
    layerType: "patterns:diamond",
    style: "simple",
    size: 30,
    color1: "#2c3e50",
    color2: "#ecf0f1",
    gap: 2,
  },
  argyle: {
    layerType: "patterns:diamond",
    style: "argyle",
    size: 40,
    color1: "#c0392b",
    color2: "#f5b7b1",
    color3: "#1a5276",
    gap: 0,
  },
  "nested-diamond": {
    layerType: "patterns:diamond",
    style: "nested",
    size: 36,
    color1: "#8e44ad",
    color2: "#f5eef8",
    gap: 2,
  },
  "adjointed-diamonds": {
    layerType: "patterns:diamond",
    style: "adjointed",
    size: 24,
    color1: "#27ae60",
    color2: "#d5f5e3",
    gap: 1,
  },
  "diamond-lattice": {
    layerType: "patterns:diamond",
    style: "lattice",
    size: 28,
    color1: "#2980b9",
    color2: "#d6eaf8",
    gap: 2,
  },

  // Hexagon presets (5)
  honeycomb: {
    layerType: "patterns:hexagon",
    style: "honeycomb",
    size: 24,
    color1: "#f39c12",
    color2: "#fef9e7",
    gap: 2,
  },
  "interlocked-hex": {
    layerType: "patterns:hexagon",
    style: "interlocked",
    size: 30,
    color1: "#2c3e50",
    color2: "#d5d8dc",
    gap: 1,
  },
  "hex-flower": {
    layerType: "patterns:hexagon",
    style: "flower",
    size: 28,
    color1: "#e74c3c",
    color2: "#fadbd8",
    gap: 2,
  },
  "hex-grid": {
    layerType: "patterns:hexagon",
    style: "grid",
    size: 20,
    color1: "#1a5276",
    color2: "#d4e6f1",
    gap: 2,
  },
  "overlapping-hex": {
    layerType: "patterns:hexagon",
    style: "overlapping",
    size: 32,
    color1: "#16a085",
    color2: "#d1f2eb",
    gap: 0,
  },

  // Star presets (5)
  "six-pointed": {
    layerType: "patterns:star",
    style: "six-pointed",
    size: 28,
    color1: "#2c3e50",
    color2: "#ecf0f1",
    gap: 2,
  },
  "eight-pointed": {
    layerType: "patterns:star",
    style: "eight-pointed",
    size: 32,
    color1: "#8e44ad",
    color2: "#f5eef8",
    gap: 2,
  },
  "plus-grid": {
    layerType: "patterns:star",
    style: "plus-grid",
    size: 20,
    color1: "#c0392b",
    color2: "#ffffff",
    gap: 4,
  },
  "plus-offset": {
    layerType: "patterns:star",
    style: "plus-offset",
    size: 18,
    color1: "#27ae60",
    color2: "#eafaf1",
    gap: 4,
  },
  "star-lattice": {
    layerType: "patterns:star",
    style: "lattice",
    size: 36,
    color1: "#d4ac0d",
    color2: "#fef9e7",
    gap: 1,
  },

  // Circle presets (6)
  "concentric-rings": {
    layerType: "patterns:circle",
    style: "concentric",
    size: 40,
    color1: "#2c3e50",
    color2: "#ecf0f1",
    lineWidth: 2,
    gap: 6,
  },
  "overlapping-circles": {
    layerType: "patterns:circle",
    style: "overlapping",
    size: 30,
    color1: "#2980b9",
    color2: "#d6eaf8",
    lineWidth: 1.5,
    gap: 0,
  },
  "packed-circles": {
    layerType: "patterns:circle",
    style: "packed",
    size: 24,
    color1: "#e74c3c",
    color2: "#ffffff",
    gap: 2,
  },
  "semicircle-row": {
    layerType: "patterns:circle",
    style: "semicircle",
    size: 28,
    color1: "#16a085",
    color2: "#d1f2eb",
    gap: 2,
  },
  "quarter-turn": {
    layerType: "patterns:circle",
    style: "quarter-turn",
    size: 32,
    color1: "#8e44ad",
    color2: "#f5eef8",
    lineWidth: 2,
    gap: 2,
  },
  bullseye: {
    layerType: "patterns:circle",
    style: "bullseye",
    size: 36,
    color1: "#c0392b",
    color2: "#ffffff",
    lineWidth: 3,
    gap: 4,
  },

  // Japanese presets (6)
  asanoha: {
    layerType: "patterns:japanese",
    style: "asanoha",
    size: 30,
    color1: "#2c3e50",
    color2: "#f5f5dc",
    lineWidth: 1,
  },
  seigaiha: {
    layerType: "patterns:japanese",
    style: "seigaiha",
    size: 28,
    color1: "#1a5276",
    color2: "#d4e6f1",
    lineWidth: 1.5,
  },
  shippo: {
    layerType: "patterns:japanese",
    style: "shippo",
    size: 24,
    color1: "#8e44ad",
    color2: "#f5eef8",
    lineWidth: 1,
  },
  "bishamon-kikko": {
    layerType: "patterns:japanese",
    style: "bishamon-kikko",
    size: 32,
    color1: "#c0392b",
    color2: "#fadbd8",
    lineWidth: 1.5,
  },
  yagasuri: {
    layerType: "patterns:japanese",
    style: "yagasuri",
    size: 26,
    color1: "#27ae60",
    color2: "#eafaf1",
    lineWidth: 1,
  },
  kumiko: {
    layerType: "patterns:japanese",
    style: "kumiko",
    size: 34,
    color1: "#d4ac0d",
    color2: "#fef9e7",
    lineWidth: 1,
  },

  // Lattice presets (5)
  "greek-key": {
    layerType: "patterns:lattice",
    style: "greek-key",
    size: 30,
    color1: "#2c3e50",
    color2: "#ecf0f1",
    lineWidth: 2,
  },
  "chinese-fret": {
    layerType: "patterns:lattice",
    style: "chinese-fret",
    size: 28,
    color1: "#c0392b",
    color2: "#fadbd8",
    lineWidth: 1.5,
  },
  "double-meander": {
    layerType: "patterns:lattice",
    style: "double-meander",
    size: 36,
    color1: "#1a5276",
    color2: "#d4e6f1",
    lineWidth: 2,
  },
  "chinese-window": {
    layerType: "patterns:lattice",
    style: "chinese-window",
    size: 32,
    color1: "#8e44ad",
    color2: "#f5eef8",
    lineWidth: 1.5,
  },
  "interlocking-fret": {
    layerType: "patterns:lattice",
    style: "interlocking-fret",
    size: 24,
    color1: "#d4ac0d",
    color2: "#fef9e7",
    lineWidth: 1.5,
  },

  // Plaid presets (4)
  tartan: {
    layerType: "patterns:plaid",
    style: "tartan",
    size: 40,
    color1: "#c0392b",
    color2: "#1a5276",
    color3: "#27ae60",
  },
  "buffalo-plaid": {
    layerType: "patterns:plaid",
    style: "buffalo-plaid",
    size: 36,
    color1: "#c0392b",
    color2: "#1a1a1a",
  },
  madras: {
    layerType: "patterns:plaid",
    style: "madras",
    size: 44,
    color1: "#e74c3c",
    color2: "#f39c12",
    color3: "#2980b9",
  },
  windowpane: {
    layerType: "patterns:plaid",
    style: "windowpane",
    size: 48,
    color1: "#2c3e50",
    color2: "#ecf0f1",
  },

  // Cube presets (3)
  "isometric-cube": {
    layerType: "patterns:cube",
    style: "isometric",
    size: 30,
    color1: "#2c3e50",
    color2: "#5d6d7e",
    color3: "#85929e",
    gap: 1,
  },
  "stacked-cubes": {
    layerType: "patterns:cube",
    style: "stacked",
    size: 36,
    color1: "#c0392b",
    color2: "#e74c3c",
    color3: "#f1948a",
    gap: 1,
  },
  "tumbling-blocks": {
    layerType: "patterns:cube",
    style: "tumbling-blocks",
    size: 28,
    color1: "#1a5276",
    color2: "#2980b9",
    color3: "#85c1e9",
    gap: 0,
  },

  // Leaf presets (4)
  "simple-leaf": {
    layerType: "patterns:leaf",
    style: "simple-leaf",
    size: 28,
    color1: "#27ae60",
    color2: "#eafaf1",
    gap: 8,
  },
  "fern-row": {
    layerType: "patterns:leaf",
    style: "fern-row",
    size: 32,
    color1: "#1e8449",
    color2: "#d5f5e3",
    gap: 6,
  },
  "tropical-scatter": {
    layerType: "patterns:leaf",
    style: "tropical-scatter",
    size: 40,
    color1: "#196f3d",
    color2: "#fef9e7",
    gap: 10,
  },
  "vine-trail": {
    layerType: "patterns:leaf",
    style: "vine-trail",
    size: 24,
    color1: "#27ae60",
    color2: "#f0f3f4",
    gap: 4,
  },

  // Floral presets (5)
  daisy: {
    layerType: "patterns:floral",
    style: "daisy",
    size: 30,
    color1: "#f1c40f",
    color2: "#ecf0f1",
    petalCount: 8,
    gap: 6,
  },
  rosette: {
    layerType: "patterns:floral",
    style: "rosette",
    size: 36,
    color1: "#e74c3c",
    color2: "#fadbd8",
    petalCount: 12,
    gap: 4,
  },
  "cherry-blossom": {
    layerType: "patterns:floral",
    style: "cherry-blossom",
    size: 24,
    color1: "#f5b7b1",
    color2: "#fef9e7",
    petalCount: 5,
    gap: 8,
  },
  sunflower: {
    layerType: "patterns:floral",
    style: "sunflower",
    size: 40,
    color1: "#f39c12",
    color2: "#196f3d",
    petalCount: 16,
    gap: 4,
  },
  "abstract-flower": {
    layerType: "patterns:floral",
    style: "abstract-flower",
    size: 32,
    color1: "#8e44ad",
    color2: "#d2b4de",
    petalCount: 6,
    gap: 10,
  },

  // Memphis presets (4)
  "memphis-classic": {
    layerType: "patterns:memphis",
    style: "classic",
    size: 20,
    color1: "#e74c3c",
    color2: "#f1c40f",
    color3: "#3498db",
    density: 40,
  },
  "confetti-burst": {
    layerType: "patterns:memphis",
    style: "confetti",
    size: 12,
    color1: "#2ecc71",
    color2: "#e74c3c",
    color3: "#9b59b6",
    density: 60,
  },
  "geometric-scatter": {
    layerType: "patterns:memphis",
    style: "geometric",
    size: 24,
    color1: "#2c3e50",
    color2: "#ecf0f1",
    density: 30,
  },
  "squiggle-field": {
    layerType: "patterns:memphis",
    style: "squiggle",
    size: 18,
    color1: "#e67e22",
    color2: "#fef9e7",
    density: 35,
  },

  // Eye presets (4)
  "vesica-piscis": {
    layerType: "patterns:eye",
    style: "vesica",
    size: 30,
    color1: "#2c3e50",
    color2: "#ecf0f1",
    lineWidth: 1.5,
    gap: 2,
  },
  "evil-eye": {
    layerType: "patterns:eye",
    style: "pointed",
    size: 28,
    color1: "#1a5276",
    color2: "#d4e6f1",
    lineWidth: 2,
    gap: 4,
  },
  "almond-lattice": {
    layerType: "patterns:eye",
    style: "almond",
    size: 24,
    color1: "#8e44ad",
    color2: "#f5eef8",
    lineWidth: 1,
    gap: 1,
  },
  "nested-eyes": {
    layerType: "patterns:eye",
    style: "double",
    size: 36,
    color1: "#c0392b",
    color2: "#fadbd8",
    lineWidth: 1.5,
    gap: 3,
  },

  // Spiral presets (4)
  "tight-spiral": {
    layerType: "patterns:spiral",
    style: "archimedean",
    size: 30,
    color1: "#2c3e50",
    color2: "#ecf0f1",
    lineWidth: 1.5,
    gap: 6,
  },
  scrollwork: {
    layerType: "patterns:spiral",
    style: "scroll",
    size: 36,
    color1: "#d4ac0d",
    color2: "#fef9e7",
    lineWidth: 2,
    gap: 4,
  },
  "double-spiral": {
    layerType: "patterns:spiral",
    style: "double",
    size: 32,
    color1: "#8e44ad",
    color2: "#f5eef8",
    lineWidth: 1.5,
    gap: 8,
  },
  "batik-swirl": {
    layerType: "patterns:spiral",
    style: "logarithmic",
    size: 28,
    color1: "#784212",
    color2: "#fef9e7",
    lineWidth: 1,
    gap: 5,
  },

  // Terrazzo presets (3)
  "terrazzo-classic": {
    layerType: "patterns:terrazzo",
    style: "classic",
    size: 16,
    color1: "#2c3e50",
    color2: "#ecf0f1",
    color3: "#c0392b",
    density: 40,
  },
  "terrazzo-bold": {
    layerType: "patterns:terrazzo",
    style: "bold",
    size: 28,
    color1: "#e74c3c",
    color2: "#f1c40f",
    color3: "#3498db",
    density: 25,
  },
  "blob-scatter": {
    layerType: "patterns:terrazzo",
    style: "blob",
    size: 20,
    color1: "#27ae60",
    color2: "#d5f5e3",
    density: 35,
  },

  // Square presets (5)
  "nested-squares": {
    layerType: "patterns:square",
    style: "nested",
    size: 30,
    color1: "#2c3e50",
    color2: "#ecf0f1",
    gap: 2,
  },
  "rotated-squares": {
    layerType: "patterns:square",
    style: "rotated",
    size: 28,
    color1: "#c0392b",
    color2: "#fadbd8",
    gap: 3,
  },
  "squares-and-stars": {
    layerType: "patterns:square",
    style: "stars-and-squares",
    size: 32,
    color1: "#1a5276",
    color2: "#d4e6f1",
    color3: "#f39c12",
    gap: 1,
  },
  "squares-and-circles": {
    layerType: "patterns:square",
    style: "circles-and-squares",
    size: 34,
    color1: "#8e44ad",
    color2: "#f5eef8",
    gap: 2,
  },
  "offset-squares": {
    layerType: "patterns:square",
    style: "offset",
    size: 26,
    color1: "#27ae60",
    color2: "#eafaf1",
    gap: 3,
  },

  // Octagon presets (2)
  "octagon-square": {
    layerType: "patterns:octagon",
    style: "octagon-square",
    size: 30,
    color1: "#2c3e50",
    color2: "#bdc3c7",
    gap: 2,
  },
  "octagon-outline": {
    layerType: "patterns:octagon",
    style: "outline",
    size: 28,
    color1: "#1a5276",
    color2: "#ecf0f1",
    lineWidth: 1.5,
  },

  // Scale presets (4)
  "fishscale-classic": {
    layerType: "patterns:scale",
    style: "fishscale",
    size: 24,
    color1: "#2c3e50",
    color2: "#ecf0f1",
    lineWidth: 1,
  },
  "scallop-shell": {
    layerType: "patterns:scale",
    style: "scallop",
    size: 28,
    color1: "#1a5276",
    color2: "#d4e6f1",
    lineWidth: 1.5,
  },
  "overlapping-scales": {
    layerType: "patterns:scale",
    style: "overlapping",
    size: 22,
    color1: "#8e44ad",
    color2: "#f5eef8",
    lineWidth: 1,
  },
  "pointed-scales": {
    layerType: "patterns:scale",
    style: "pointed",
    size: 26,
    color1: "#c0392b",
    color2: "#fadbd8",
    lineWidth: 1.5,
  },

  // Chainlink presets (3)
  "chainlink-fence": {
    layerType: "patterns:chainlink",
    style: "circle",
    size: 24,
    color1: "#7f8c8d",
    color2: "#ecf0f1",
    lineWidth: 2,
    gap: 4,
  },
  "chain-mail": {
    layerType: "patterns:chainlink",
    style: "oval",
    size: 20,
    color1: "#5d6d7e",
    color2: "#f0f3f4",
    lineWidth: 1.5,
    gap: 2,
  },
  "interlocking-rings": {
    layerType: "patterns:chainlink",
    style: "double",
    size: 28,
    color1: "#d4ac0d",
    color2: "#fef9e7",
    lineWidth: 1.5,
    gap: 3,
  },

  // Ethnic presets (6)
  "tribal-zigzag": {
    layerType: "patterns:ethnic",
    style: "tribal-zigzag",
    size: 24,
    color1: "#784212",
    color2: "#fef9e7",
    lineWidth: 2,
  },
  "african-kente": {
    layerType: "patterns:ethnic",
    style: "african-kente",
    size: 30,
    color1: "#f39c12",
    color2: "#1a5276",
    lineWidth: 1.5,
  },
  "egyptian-lotus": {
    layerType: "patterns:ethnic",
    style: "egyptian-lotus",
    size: 32,
    color1: "#d4ac0d",
    color2: "#1a5276",
    lineWidth: 1.5,
  },
  "mexican-step": {
    layerType: "patterns:ethnic",
    style: "mexican-step",
    size: 26,
    color1: "#c0392b",
    color2: "#f1c40f",
    lineWidth: 2,
  },
  "songket-diamond": {
    layerType: "patterns:ethnic",
    style: "songket-diamond",
    size: 28,
    color1: "#8e44ad",
    color2: "#f5eef8",
    lineWidth: 1.5,
  },
  "tribal-arrow": {
    layerType: "patterns:ethnic",
    style: "tribal-arrow",
    size: 22,
    color1: "#2c3e50",
    color2: "#ecf0f1",
    lineWidth: 2,
  },

  // Batch 5 — Expanded presets for existing types

  // Wave expanded presets (4)
  "deep-wave": {
    layerType: "patterns:wave",
    amplitude: 40,
    frequency: 1.5,
    phase: 0,
    lineWidth: 3,
    waveform: "sine",
    color: "#1a5276",
    spacing: 20,
  },
  "nested-wave": {
    layerType: "patterns:wave",
    amplitude: 12,
    frequency: 4,
    phase: 0,
    lineWidth: 1,
    waveform: "sine",
    color: "#2c3e50",
    spacing: 6,
  },
  "square-wave": {
    layerType: "patterns:wave",
    amplitude: 15,
    frequency: 3,
    phase: 0,
    lineWidth: 2,
    waveform: "square",
    color: "#8e44ad",
    spacing: 12,
  },
  "sawtooth-wave": {
    layerType: "patterns:wave",
    amplitude: 18,
    frequency: 2.5,
    phase: 0,
    lineWidth: 2,
    waveform: "sawtooth",
    color: "#c0392b",
    spacing: 14,
  },

  // Herringbone expanded presets (3)
  "wide-chevron": {
    layerType: "patterns:herringbone",
    blockWidth: 50,
    blockHeight: 16,
    angle: 0,
    color1: "#2c3e50",
    color2: "#bdc3c7",
    gap: 2,
  },
  "thin-chevron": {
    layerType: "patterns:herringbone",
    blockWidth: 24,
    blockHeight: 8,
    angle: 0,
    color1: "#1a5276",
    color2: "#d4e6f1",
    gap: 1,
  },
  "double-chevron": {
    layerType: "patterns:herringbone",
    blockWidth: 36,
    blockHeight: 12,
    angle: 45,
    color1: "#c0392b",
    color2: "#fadbd8",
    gap: 3,
  },

  // Tile expanded presets (3)
  "ogee-tile": {
    layerType: "patterns:tile",
    tileShape: "ogee",
    size: 32,
    color1: "#1a5276",
    color2: "#d4e6f1",
    gap: 2,
  },
  "lantern-tile": {
    layerType: "patterns:tile",
    tileShape: "lantern",
    size: 28,
    color1: "#d4ac0d",
    color2: "#fef9e7",
    gap: 3,
  },
  "basketweave-tight": {
    layerType: "patterns:tile",
    tileShape: "basketweave-tight",
    size: 20,
    color1: "#8e44ad",
    color2: "#f5eef8",
    gap: 1,
  },

  // Stripe expanded presets (2)
  railroad: {
    layerType: "patterns:stripe",
    angle: 0,
    spacing: 24,
    lineWidth: 4,
    colors: ["#2c3e50", "#bdc3c7"],
    dashPattern: [12, 8],
  },
  "diagonal-stripe": {
    layerType: "patterns:stripe",
    angle: 45,
    spacing: 18,
    lineWidth: 8,
    colors: ["#f39c12", "#ffffff"],
  },

  // Crosshatch-geo expanded presets (2)
  "triple-crosshatch": {
    layerType: "patterns:crosshatch-geo",
    angle1: 0,
    angle2: 60,
    spacing: 10,
    lineWidth: 1,
    color: "#2c3e50",
    backgroundColor: "#ecf0f1",
  },
  "wide-mesh": {
    layerType: "patterns:crosshatch-geo",
    angle1: 0,
    angle2: 90,
    spacing: 20,
    lineWidth: 3,
    color: "#7f8c8d",
    backgroundColor: "#f0f3f4",
  },

  // Checker expanded presets (2)
  "checkerboard-diagonal": {
    layerType: "patterns:checker",
    cellSize: 20,
    colors: ["#2c3e50", "#ecf0f1"],
    angle: 45,
  },
  "pixel-grid": {
    layerType: "patterns:checker",
    cellSize: 6,
    colors: ["#1a1a2e", "#e8e8e8"],
    angle: 0,
  },

  // Dot expanded presets (2)
  bubble: {
    layerType: "patterns:dot",
    spacing: 28,
    radius: 10,
    offset: true,
    color: "#3498db",
    backgroundColor: "#eaf2f8",
  },
  "ring-dot": {
    layerType: "patterns:dot",
    spacing: 22,
    radius: 6,
    offset: false,
    color: "#8e44ad",
    backgroundColor: "#f5eef8",
  },
};

/** Look up a pattern preset by name. Returns undefined if not found. */
export function getPatternPreset(name: string): PatternPreset | undefined {
  return PATTERN_PRESETS[name];
}

/** Look up a geometric preset by name. Returns undefined if not found. */
export function getGeometricPreset(name: string): GeometricPreset | undefined {
  return GEOMETRIC_PRESETS[name];
}

/**
 * Resolve a strategy value: if it's a string preset name, expand it.
 * Otherwise return as-is. Returns null if the preset name is unknown.
 */
export function resolveStrategy(
  strategyOrPreset: PatternStrategy | string,
): { strategy: PatternStrategy; lineWidth?: number } | null {
  if (typeof strategyOrPreset === "string") {
    const preset = PATTERN_PRESETS[strategyOrPreset];
    if (!preset) return null;
    return { strategy: preset.strategy, lineWidth: preset.lineWidth };
  }
  return { strategy: strategyOrPreset };
}
